### ISSUE TITLE
[Feature request] Change the gender “template” (German) 

### ISSUE THREAD

**Issue by Immunize2** [abdnh/anki-zim-reader#14]
German nouns have 3 grammatical genders:
- Feminine
- Masculine
- Neuter

The German Wiktionary shows the data only with an abbreviation :
f , m , n

![grafik](https://user-images.githubusercontent.com/111645935/194960106-60c1fb52-1951-4d9f-9c03-6012f18d20b7.png)

It is desirable to write into Anki cards the gender exactly as in the online version of the Wiktionary : f, m, n

Currently, the add-on writes into cards:

![grafik](https://user-images.githubusercontent.com/111645935/194960355-0b8888e2-4f1a-4b6a-8c10-eec86f0c90f5.png)

The problem with that "verbose" method is that it is impossible to automatically color Anki cards with such long descriptions in the Gender field. 

If someone wants to add color into cards just needs a single letter (lowercase) as in the online Wiktionary.

**Therefore, could the add-on display the gender in cards exactly as the online German Wiktionary ?**
**m
f
n**

**Comment by Immunize2** [comment]
Here is my method to automatically change the background depending on the Grammatical Gender:
Front:
![grafik](https://user-images.githubusercontent.com/111645935/194960754-ed1f9c21-af31-46dd-bb91-128052f85c3b.png)
Back:
![grafik](https://user-images.githubusercontent.com/111645935/194960773-63ddc956-e218-4d2e-976a-8ade5407880d.png)

**Front Field:**
<div class="background-div {{Genus}}"></div>
xxxx

**Back Field:**
<div class="background-div {{Genus}}"></div>
xxxx

**Style:**
![grafik](https://user-images.githubusercontent.com/111645935/194961038-d62c952d-698f-49ac-b146-ca28c9e99a6d.png)

**Comment by abdnh** [comment]
Should be easy to change.
One question: How do you suggest we deal with words with multiple genders? Take "Zeit" for example. If we extract all gender abbreviations, then multiple gender classes will apply and the styles of the last matching one in your template will rule. I'm inclined to just paste all genders like `f m`.

**Comment by Immunize2** [comment]
> I'm inclined to just paste all genders like f m.

Totally agree !

Writing both genders is the best solution.

Thanks for your good work !
