### ISSUE TITLE
Critical Bug

### ISSUE THREAD

**Issue by Immunize2** [abdnh/anki-zim-reader#16]
OS: Manjaro Stable
Anki: Latest Stable (not beta)

After updating the add-on today, I get an error and cannot use the add-on:

![grafik](https://user-images.githubusercontent.com/111645935/204110035-b7ed4766-9ce8-46ed-9897-2a6782310532.png)

**Comment by abdnh** [comment]
Should be fixed now. I usually run the add-on in a way that doesn't trigger this error, so thanks for the report!
