### ISSUE TITLE
[Feature] Automatically resize images added from Wiktionary

### ISSUE THREAD

**Issue by Memory383** [abdnh/anki-zim-reader#19]
The images from the Wiktionary in .zim format are very small.

When one tries to see the images on Anki the size is not adequate and then one needs to manually resize.

**Would it be possible an option to automatically resize the images to a "default value" with the add-on ?**

For example > 800 x 800 or something similar conserving the original size ratio.

------------
Here is the "original size": 
![grafik](https://user-images.githubusercontent.com/121114125/209880518-c4b70453-ff8f-4be4-8209-6fc49e8c2f64.png)

![grafik](https://user-images.githubusercontent.com/121114125/209880541-66f43c69-8f1d-446f-9672-b5a575a76338.png)

**Comment by abdnh** [comment]
Doesn't adding something like this in your styling section work?

```css
img {
  min-width: 800px;
}
```

**Comment by Memory383** [comment]
works fine ! Thanks !!!
