### ISSUE TITLE
[Feature Request] Adding images from .zim files

### ISSUE THREAD

**Issue by Immunize2** [abdnh/anki-zim-reader#5]
**Would it be possible to add into Anki images from .zim files ?**

The German Wiktionary currently has 27.000 images:
https://de.wiktionary.org/wiki/Benutzer:QuiverT123

Articles with images show a predictable pattern in the HTML:
https://de.wiktionary.org/wiki/Bruder
https://de.wiktionary.org/wiki/Hobo
https://de.wiktionary.org/wiki/Dame

Images in .zim Wiktionary can be seen perfectly with [GoldenDict by Xiaoyifang](https://github.com/xiaoyifang/goldendict):

![grafik](https://user-images.githubusercontent.com/111645935/193477856-02a2601e-101b-4229-9dc4-746cf2ac1618.png)

![grafik](https://user-images.githubusercontent.com/111645935/193477871-291aa7cf-deaa-4c4d-917c-d222e760f1eb.png)

-----------
PS. @abdnh I strongly recommend you to install GoldenDict by Xiaoyifang instead of the Official build. It is much better. After installation you can download dictionaries here:
https://downloads.freemdict.com/

Part of that collection is maintained by me (Ru-Board). We have Arabic Dictionaries too :D

**Comment by Immunize2** [comment]
If adding images from .zim files is too difficult, do not worry. Never mind.

 It would be a very nice addition, but it might be really hard. Each Wiktionary has different HTML structure for images. A nightmare !

**Comment by abdnh** [comment]
> Articles with images show a predictable pattern in the HTML

I agree. I think it's easy to add support for images. I'm thinking of adding a separate field for images. If you have other suggestions, let me know!

>I strongly recommend you to install GoldenDict by Xiaoyifang instead of the Official build

Already using it! I'm very happy to have found this fork after struggling with the official build not being able to access a [simple website](https://github.com/abdnh/trdict) months ago!

**Comment by abdnh** [comment]
I've added a field for images. You can download the update from the "Artifacts" section here: https://github.com/abdnh/anki-zim-reader/actions/runs/3181066857

> Articles with images show a predictable pattern in the HTML:
> https://de.wiktionary.org/wiki/Bruder
> https://de.wiktionary.org/wiki/Hobo
> https://de.wiktionary.org/wiki/Dame

Note that out of these words, only "Dame" has images stored in the actual ZIM file for some reason (Tested with wiktionary_de_all_maxi_2022-09).

**Comment by Immunize2** [comment]
> Note that out of these words, only "Dame" has images stored in the actual ZIM file for some reason (Tested with wiktionary_de_all_maxi_2022-09).

I added the images for "Bruder" and "Hobo" few days ago. I am editor at the German Wiktionary. So, the .zim file does not include those images because the scraper of the Kiwix project worked before my additions.

On the other hand, there is a bug on Wikimedia Software where sometimes images in the German Wiktionary are not shown on .zim files.

 I already discussed that problem with the founder of Kiwix and I will have to report the bug directly to Wikimedia Foundation. I will do it right now... 

So, do not worry if sometimes images do not appear. I will send you the bug report so that you can  better understand it.

Thanks for your great job  !

**Comment by Immunize2** [comment]
> I've added a field for images....

Works perfectly with images ! Thank you very much !

By the way, I just filled a bug to Wikimedia Foundation about the missing images on .zim files: https://phabricator.wikimedia.org/T319303
