### ISSUE TITLE
[Feature Request] Add data into cards without using the GUI (new shortcut)

### ISSUE THREAD

**Issue by Immunize2** [abdnh/anki-zim-reader#6]
Whenever a user tries to add data from a .zim file the GUI would appear to confirm the settings. 

That behavior makes sense for bulk-editing, but the option to “Add Cards” individually also shows the GUI every time that a new card is made. It is time-consuming if someone adds +50 cards per day.

**Is it possible to add a shortcut that would automatically “fill” the new card without showing the GUI ?**

_For example:_ 
CTRL + S  = shows GUI with options
CRTL + D = automatically fills the card without showing the GUI

**Comment by abdnh** [comment]
Won't adding the cards with only the Word field filled in, then filling the dictionary info in bulk from the browser be even faster?

**Comment by Immunize2** [comment]
You are right. Adding another shortcut is not really important. Just an idea... I will close this issue for now. 

Thanks for the great work !
