### ISSUE TITLE
[Feature Request] Option to skip cards that have content in a field

### ISSUE THREAD

**Issue by Immunize2** [abdnh/anki-zim-reader#8]
Some cards might have content in a field and it might be desirable to skip them.

For example:

If someone manually adds an example that is better than the Wiktionary, the add-on will REPLACE the example and users have no choice.

There is an add-on to automatically fill anki cards from .mdx dictionaries that has an option to "skip fields with content". 

![grafik](https://user-images.githubusercontent.com/111645935/193619468-d2e44dd5-8330-4476-8180-af56064ae467.png)

https://ankiweb.net/shared/info/1807206748

**Could we have an option in the GUI to skip fields that already have content ?**

**Comment by abdnh** [comment]
This is nice to have. Will look into it.

**Comment by abdnh** [comment]
Done.
